# -*- coding: utf-8 -*-
"""codingtest4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ko6f-V-7akQaoPB3ngMReITnhGJoyQSx
"""

order=[]
k=[]
for rec in record:
  k=rec.split()
  if len(k)==3:
    print(rec)
    F,Id,nic=rec.split()
    Enter(F,Id,nic)
    #들어온순서 아이디와 함수 저장
  else:
    print(rec)
    F,Id=rec.split()
  order.append((Id,F))

result=[]
for Id,F in order:
  if F =='Enter':
    st=Idlist[Id]+"님이 들어왔습니다."
  elif F=='Leave':
    st=Idlist[Id]+"님이 나갔습니다."
  result.append(st)

def Enter(F,Id,nic):
  #추가
  Idlist[Id]=nic

